// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hucqxocntkexrkwzymfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Y3F4b2NudGtleHJrd3p5bWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTk5NzUsImV4cCI6MjA3Mjk5NTk3NX0.kUjcSejiPxeID0M68bY5EhVJRLQdpujzOv3uJDuzqvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});